<a href="https://colab.research.google.com/github/quaziharis/machine_Learning/blob/master/Creditcard_Fraud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install pandas --upgrade pandas_profiling


Requirement already up-to-date: pandas in /usr/local/lib/python3.6/dist-packages (1.0.3)
Requirement already up-to-date: pandas_profiling in /usr/local/lib/python3.6/dist-packages (2.6.0)


In [0]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
import seaborn as sns
import pandas_profiling
from pandas_profiling import ProfileReport
from sklearn.preprocessing import MinMaxScaler

In [0]:
sns.pairplot(df)

In [0]:
df=df.dropna()

In [0]:
x=df.iloc[:,:-1].values
sc=MinMaxScaler()
x=sc.fit_transform(x)
y=df.iloc[:,30].values
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=0,stratify=y)

In [0]:
lr=LogisticRegression()
lr.fit(xtrain,ytrain)
print("training Acc for logistic",lr.score(xtrain,ytrain))
print('testing acc for logisitc',lr.score(xtest,ytest))
ypred=lr.predict(xtest)
confusion_matrix1=confusion_matrix(ytest,ypred)
print('confusion mertix for logistic')
sns.heatmap(confusion_matrix1, annot=True,cmap='Blues')
print(confusion_matrix1)
print('classification report for logistic')
print(classification_report(ytest,ypred))

training Acc for logistic 0.9986444033222878
testing acc for logisitc 0.998644408183758
confusion mertix for logistic
[[39747     9]
 [   45    34]]
classification report for logistic
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     39756
         1.0       0.79      0.43      0.56        79

    accuracy                           1.00     39835
   macro avg       0.89      0.72      0.78     39835
weighted avg       1.00      1.00      1.00     39835



In [0]:
from sklearn.ensemble import RandomForestClassifier
RC=RandomForestClassifier(n_estimators=300,max_depth=20)
RC.fit(xtrain,ytrain)
print(" training acc for random forest ",RC.score(xtrain,ytrain))
print("testing acc for randomforest",RC.score(xtest,ytest))
ypred=RC.predict(xtest)
print('Classification Report for random forest')
print(classification_report(ytest,ypred))
print('confusion matrix for random forest')
confusion_matrix2=confusion_matrix(ytest,ypred)
sns.heatmap(confusion_matrix2, annot=True,cmap='Blues')
print(confusion_matrix2)

 training acc for random forest  1.0
testing acc for randomforest 0.9995481360612527
Classification Report for random forest
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     39756
         1.0       0.97      0.80      0.88        79

    accuracy                           1.00     39835
   macro avg       0.98      0.90      0.94     39835
weighted avg       1.00      1.00      1.00     39835

confusion matrix for random forest
[[39754     2]
 [   16    63]]


In [0]:
from sklearn.ensemble import AdaBoostClassifier
ada=AdaBoostClassifier(RandomForestClassifier())
ada.fit(xtrain,ytrain)
ypred=ada.predict(xtest)
print('Classification Report for random forest')
print(classification_report(ytest,ypred))
print('confusion matrix for random forest')
confusion_matrix2=confusion_matrix(ytest,ypred)
sns.heatmap(confusion_matrix2, annot=True,cmap='Blues')
print(confusion_matrix2)

Classification Report for random forest
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     39756
         1.0       0.95      0.78      0.86        79

    accuracy                           1.00     39835
   macro avg       0.98      0.89      0.93     39835
weighted avg       1.00      1.00      1.00     39835

confusion matrix for random forest
[[39753     3]
 [   17    62]]
